#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=20GB
#SBATCH --time=20:00:00
#SBATCH --account=cegs
module purge
module load gcc/8.3.0
module load openblas/0.3.8
module load r/4.0.0
Rscript --vanilla script.R
